language: go
services:
  - docker
go:
  - 1.13.x
before_install:
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.4/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  # Setup test coveragae
  - chmod +x test-coverage.sh
  - go get -t -v ./...
install:
  # Install tools for auto build and release
  - curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o ~/semantic-release && chmod +x ~/semantic-release
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
before_script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test
  - go build ./cmd/subscription/
script:
  - ./test-coverage.sh
  - chmod +x release
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./release
notifications:
  email: false
